global:
  resolve_timeout: 2m

route:
  receiver: night-call
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: night-call
    webhook_configs:
      - url: http://night-call:8000/alerts
        send_resolved: true
        max_alerts: 20
